name: 'Python Linter'
description: 'Lints Python code using isort and black'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    
    - uses: isort/isort-action@v1
      with:
        args: "--check"
        src: "./src"
    
    - uses: psf/black@stable
      with:
        options: "--check"
        src: "./src"